import { ThemeProvider } from "@/components/ui/theme-provider";
import "./globals.css";
import { Inter } from "next/font/google";
import TailwindDebug from "@/components/ui/TailwindDebug";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata = {
  title: "Covid 19 Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={` ${inter.variable} font-inter p-5 min-h-screen   antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {children}
          {process.env.NODE_ENV === "development" && <TailwindDebug />}
        </ThemeProvider>
      </body>
    </html>
  );
}
